### ISSUE TITLE
2880x2160 - Impaired Scanline Behavior 

### ISSUE THREAD

**Issue by sudobbq** [marqs85/ossc_pro#10]
In 4K mode, the V interval to select "9" isn't shown.  My only choices are up to 6.  Auto (9) doesn't seem to work correctly.  Current settings available make scanlines appear too thin that make it appear the screen is darkening.

**Comment by marqs85** [comment]
Fixed in 7c14c9e1487afbb11f78b6e9370f245f62131417.
