### ISSUE TITLE
Add Option to Activate on Power On

### ISSUE THREAD

**Issue by PARTYMANX** [marqs85/ossc_pro#13]
I would like to use the OSSC Pro inside an arcade cabinet, which means I also want to have the OSSC Pro start up with power being applied instead of going to standby.  I understand that power on to standby is good behavior in typical TV setups, so I'd propose either the device remembering its standby state (as consumer monitors tend to do), or adding an explicit setting to determine this behavior.

**Comment by marqs85** [comment]
Power-up state option has been added in 7c14c9e1487afbb11f78b6e9370f245f62131417.
