### ISSUE TITLE
[Feature] Add interlace output for CRT monitor 

### ISSUE THREAD

**Issue by Ibxx0403** [marqs85/ossc_pro#18]
Is it possible to implement an interlace option for CRT monitors? that interlaces the OSSC pro's output making it possible to play "current" gen consoles at high frame rates (120hz) on mid tier CRT monitors that cannot do lets say 720p 120hz. It would also make it possible to play 1440p60 content.

**Comment by marqs85** [comment]
Interlaced output is already possible but I'm not sure which CRT monitors you refer to as they don't typically (aside from broadcasting stuff) support interlace.

**Comment by Ibxx0403** [comment]
@marqs85 I have about 4 crt monitors and all of them can take interlaced output from either my ps5 or my old windows laptop using CRU. Most CRT monitors can't take 480i at 60 hz because of the Horizontal Scanning Frequency is under the 31 kHz. From my testing most CRTs can handle any type of input as long as bandwidth, Horizontal Scanning Frequency doesn't go over the specified limit. And as interlaced halves Horizontal Scanning Frequency it makes it possible to run higher res or nearly double the framerate on the CRT.  The types of interlaced outputs I am talking about is like 720i 120hz or 1080i 120hz or 1440i 60hz, which I couldn't see as supported output formats when I looked at the supported outputs of the ossc pro. It would also be cool if by interlacing the 1440p output if it could go over 60hz to 120hz. 

As I currently doesn't have my windows laptop near me, the only screen shot I can provide of running interlaced content on my CRTs is from my PS5 as my MacBook doesn't allow for interlaced output. 

![IMG_2260](https://github.com/marqs85/ossc_pro/assets/148635617/031b014b-9360-4a10-b396-533b99679362)

As you can see the Horizontal Scanning Frequency is about half of 1920x1080p 60hz (64-67 kHz). Making it possible to run 1920x1080 content on my CRT, that normally makes the screen go blank if its progressive scan. 

EDIT: 
Another question, that is more about the VRR implementation. When the OSSC pro outputs VRR does it force VRR without checking if the monitor is capable? if so its should apparently be possible to do some VRR on some CRT monitors. Also does it work with modern consoles such as PS5, as it doesn't implement freesync but HDMI forum VRR. As it would be really cool to see a CRT used on a modern console at 120hz VRR.

**Comment by marqs85** [comment]
I've heard some people successfully driving 240p120 to monitors specced to 640x480_60 which relies on same idea. However, I wouldn't expect effective vertical resolution to double via interlace if the fields are already the maximum height intended for the CRT. Doubling the refresh rate instead of height with interlace could be more useful, though.

1920x1080i preset refresh range could be easily bumped to 120 while 720i and 1440i would just need new presets added under CRT output modes. Those can be implemented for next FW.

**Comment by marqs85** [comment]
Regarding VRR, it's currently just a flag for the HDMI receiver intended to switch to a mode more tolerant to different refresh rates. EDID for the HDMI input port could be tailored to fool sources into sending video with actual variable blanking, but that would need to be directly passed to HDMI output as Pro does not yet support variable refresh rate.

**Comment by Ibxx0403** [comment]
To first answer:
That sounds really cool. I agree with you on the fact that doubling the refresh rate is the most important as there is not a single CRT to my knowledge that has a tube that is perfectly sharp at 1920x1080. The closest monitor my knowledge is either the Sony GDM FW900 (tube is capable of showing 1920x1200, but apparently not sharply) or the Eizo Flexscan F980 (sharpest CRT ever to my knowledge)

To the second answer:
It would be really cool if it could do it in the future, but from my side it was mostly just a shot in the dark.

**Comment by marqs85** [comment]
1080i range has been extended to 120Hz in ad9fbe3c6b1b9d603280f9fa84cbf8e11e6843d5. I did some testing with 1440i but decided not to include it in the end due to it hitting several limitations of the HW:
1. Scaling to 2560x1440 at 100+Hz exceeds bandwidth of the scaler processing pipeline (that operates on progressive content) in many cases.
2. Outputting 2560x1440i 120Hz without reduced blanking requires higher pixel clock than what the FPGA can run stable with
3. HDMI input does not support 2560x1440

By reducing refresh rate and/or horizontal resolution 1 and 2 could be resolved, but no. 3 remaining means 2560x1440 sources are not supported anyway, thus blocking related use-cases.

**Comment by Ibxx0403** [comment]
Sounds really cool, i now only need to have the device to test it out for myself, is there a timeline for when the OSSC Pro becomes available again? And thanks for the update.

**Comment by Ibxx0403** [comment]
i forgot to ask if the OSSC Pro changes the edid for the monitor to get the more obscure resolutions/framerates to work with the consoles as CRT monitors can do more than what the standard edid allows them to.  And on PC you would just use something like CRU, which is not available on consoles.

**Comment by marqs85** [comment]
OSSC Pro provides its own (very permissive) EDID to the device connected to HDMI input. This can be also overridden by a custom EDID file placed on SD card.

**Comment by Ibxx0403** [comment]
Thanks for the response, that is good to hear. I did some more research by asking playstation support and sadly the PS5 doesn't support 720p or 1080i 120hz output. I originally thought it was because of my HDMI/VGA adapters EDID, but sadly no. But thanks to your work it its now possible to play 120hz on a CRT monitor while playing on a PS5.

Though its a shame it's not possible to get a 1440p 120hz input downscaled to a 720p 120hz.

**Comment by Ibxx0403** [comment]
i forgot to ask if its possible to downscale 1080p 120hz to 720p 120hz? as i would imagine it to be less intensive on the hardware than 1440p 120hz. Though i am not sure if the scaling then becomes the problem with this solution. as i doubt it is as clean as 1440p to 720p.

**Comment by marqs85** [comment]
HDMI RX chip operates only up to 165MHz pixel clock so 720p120 or 1080i120 is highest you can input.

**Comment by Ibxx0403** [comment]
ok, thanks for the reply. I was just trying to see if it was possible but even if the chip could handle it, wouldn't the downscaling also be weird?

**Comment by Ibxx0403** [comment]
Just ordered the device, i am looking forward to trying it out.
