### ISSUE TITLE
[I+] - Info button on remote control - not working anymore ?

### ISSUE THREAD

**Issue by onthewaveagain** [marqs85/ossc_pro#21]
Looks like when the  Info button is pressed on the remote control, nothing shows up on screen. Think it worked with previous firmware.

**Comment by marqs85** [comment]
Perhaps a duplicate of [this](https://github.com/marqs85/ossc/issues/112)?

**Comment by onthewaveagain** [comment]
yes. I actually forgot that I disabled the OSD status option and it looks like the I+ button is linked to this option.
I think this should not be the case. the I+ button should work all the time regardless of the OSD status option.
