### ISSUE TITLE
Profile Names are never overwritten

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc_pro#3]
Hi! I renamed a bunch of my profiles on the SD card (with a hex editor), simply because having everything named `<used>` can be quite confusing. ;)

I was hoping that if I then saved them internally, the names would also be saved (as seems to be intended here:  https://github.com/marqs85/ossc_pro/blob/eb917bbfd857210481a06bde52c0d4a8b6398cad/software/sys_controller/src/userdata.c#L311C41-L311C41), but (on a cursory look) the `target_profile_name` seems to be overridden with the save slot selection name (https://github.com/marqs85/ossc_pro/blob/eb917bbfd857210481a06bde52c0d4a8b6398cad/software/sys_controller/src/menu.c#L175C29-L175C29), so in effect names never change once written.

I don't feel confident enough trying to change that myself, especially since I currently do not have a USBlaster if anything goes wrong (I should change that... ^^).

**Comment by marqs85** [comment]
Yes, a separate char buffer is needed for preserving current profile name while `target_profile_name` is used as temporary buffer to display profile names while browsing them. I've also been thinking about having text files on SD cards (profile name per line) which can be used to set names on profiles while saving them.

**Comment by ghost** [comment]
This might be superflous now with release 0.71. :)

Edit: Yep, 0.71 fixes that.
