### ISSUE TITLE
vrr support

### ISSUE THREAD

**Issue by arncht** [marqs85/ossc_pro#6]
hi,

i have the samsung g8 oled display, which supports the frequency upto 175hz. mostly i use the ossc pro for retro pc purposes (90-2001 period) - if i fix the output to 2560x1440 60hz, everything is perfect, but i miss the native frequencies (eg 70hz for the smooth vga scroll).

i expected, ossc uses vrr for the dos frequencies, but it looks inactive from the monitor side, and tries to use the default display profiles, which is limited. eg the 720p 70hz works, over that just the 60/100/120hz is supported.

did i miss something at the settings, or it does not support the hdmi vrr?

thank you,
arncht

**Comment by marqs85** [comment]
VRR is not currently supported. With framelock on, output vertical frequency is locked to input and you should be able to output 720p@70 or 2560x1440@70 (even if the recommended range says 50-60Hz with latter).

If you are looking for an option to set custom refresh rate (when framelock is off), that could be easily added in future firmware.

**Comment by arncht** [comment]
thank you for the answer. i tested, which combination is supported. it looks to me, the display has own profiles, and if the output does not fit to that, no image. which is pity, the display would be capable to show anything between 48-175hz in vrr mode. is there any chance to fix on the ossc pro side?

i tested with a plain dos text mode (720x400 70hz) on an asus geforce3:

![image](https://github.com/marqs85/ossc_pro/assets/478422/55899329-a389-4b59-92c6-11d0cf8cde24)

**Comment by marqs85** [comment]
Yes, it sounds like the display only supports certain refresh rates in non-VRR mode. It is possible to flag Pro's output as VRR even though it wouldn't actually use variable blanking time. This is planned to be added in the firmware in future.

**Comment by arncht** [comment]
It would be great, the hdr flag also works well.

**Comment by marqs85** [comment]
The flag has been added in 3269b54f9d525f3eb91be31000288882d5351c8b. It is now also possible to change the refresh rate of non-framelocked output.

**Comment by arncht** [comment]
Thank you! I'm writing my feedback here instead of creating another ticket. At 1080p, everything works as expected: the display shows, FreeSync is active, and the frequency is also correct. However, at 1440p, I only get a black screen, but not from the display (it shows if something is not okay) - I guess the OSSC sends this.
