### ISSUE TITLE
[BUG] jumping VGA input at 800x600 and above

### ISSUE THREAD

**Issue by arncht** [marqs85/ossc_pro#8]
Hi,

I have an issue with multiple analog VGA outputs. When the resolution is set to 800x600 and above, the screen continuously "jumps". Below this resolution, everything is fine. With some VGAs, if I change the input parameters, sometimes it's okay, but the next time it is buggy again. And with some VGAs, no matter what I do, it is always wrong.

I tried updating to the latest firmware and resetting the OSSC. The output resolution is irrelevant (anyway, I use 1440p 60Hz).

Best regards,

**Comment by marqs85** [comment]
Can you try if adjusting AV1-3 sync opt -> TTL Hsync Vth helps? If not, then I'm afraid this is due to an issue in the ADC chip which is described [here](https://videogameperfection.com/forums/topic/ossc-pro-av3-hv-sync-fix-for-splitfire-x68k-etc/) (with a fix that involves HW modification). So far the occurence has been limited to certain sources regardless of their output mode, though.

**Comment by arncht** [comment]
I've tried out some configurations, and while some cases help, there's no consistent setup. When something seems to work well, switching to another mode often results in it being wrong again. I've tested with the most popular cards of the millennium (3dfx Voodoo2, GeForce2 GTS, GeForce3), and it's completely ad hoc determining where and how it's not okay. Mostly, it's not functional; however, in some cases, it could work.

**Comment by marqs85** [comment]
does the red LED stay on in A-LM mode?

**Comment by marqs85** [comment]
I discovered a different issue which result to vertical jumping if H and V syncs are very closely aligned. This is on FW side and was easy to fix. Is this perhaps what you encountered instead of sync/horizontal instability which the other issue is referring to?

**Comment by arncht** [comment]
> does the red LED stay on in A-LM mode?

No, it does not. Does it show the no sync?

**Comment by arncht** [comment]
> I discovered a different issue which result to vertical jumping if H and V syncs are very closely aligned. This is on FW side and was easy to fix. Is this perhaps what you encountered instead of sync/horizontal instability which the other issue is referring to?

What does it mean? Most of the cases I just reset the ossc pro, then set the scaler with the fixed output and frequency (2560x1440 60hz). I do not refine anything else.

**Comment by marqs85** [comment]
Can you try if [this](http://www.infocult.com/m/tmp/ossc_pro_0.75_hvsyncfix.bin) test version works for you? It fixes vertical jumping which might occur with some RGBHV sources.

**Comment by arncht** [comment]
I tested it from 800x600 to 1600x1200, works well! I could check it just with one problematic card, but looks ok. 

Thank you, great job!
